"use client";

import React from "react";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

const TermsAndConditions = () => {
  return (
    <main className="px-6 py-12 max-w-5xl mx-auto space-y-10 text-[#0f172a] dark:text-[#e2e8f0]">
      
      {/* Page Title */}
      <section className="text-center space-y-4">
        <h1 className="text-4xl sm:text-5xl font-bold font-short-stack text-[#0c3baa] dark:text-[#facc15]">
          Terms & Conditions
        </h1>
        <p className="text-lg text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
          Please read these terms and conditions carefully before using BlogTalkhees.
        </p>
      </section>

      {/* Terms Content Card */}
      <Card className="p-6 md:p-8 bg-[#f4f6f9] dark:bg-[#1e293b] border border-gray-200 dark:border-zinc-700 shadow-md space-y-8 text-sm leading-relaxed text-gray-800 dark:text-gray-200">
        {[
          {
            title: "1. Acceptance of Terms",
            body: `By using BlogTalkhees, you agree to comply with and be bound by these Terms and Conditions. If you do not agree, please refrain from using the platform.`,
          },
          {
            title: "2. Use of the Service",
            body: `BlogTalkhees is provided for educational and informational purposes only. You must not use it for any illegal or harmful activities.`,
          },
          {
            title: "3. Intellectual Property",
            body: `All content, branding, and summaries generated by BlogTalkhees are the intellectual property of their respective owners. You may not reproduce or distribute any part without permission.`,
          },
          {
            title: "4. User Responsibility",
            body: `You are responsible for ensuring the blog URLs you provide are publicly accessible and do not violate copyright laws. We are not responsible for the content you submit.`,
          },
          {
            title: "5. Service Availability",
            body: `We strive to keep BlogTalkhees available, but we may suspend or terminate the service at any time for maintenance or other reasons.`,
          },
          {
            title: "6. Limitation of Liability",
            body: `BlogTalkhees is provided "as is" without warranties of any kind. We are not liable for any direct, indirect, or consequential damages arising from your use of the platform.`,
          },
          {
            title: "7. Changes to Terms",
            body: `We may modify these Terms at any time. Continued use of BlogTalkhees after changes implies acceptance of the new Terms.`,
          },
          {
            title: "8. Contact Information",
            body: `For any concerns or questions regarding these Terms & Conditions, you can reach out via GitHub or LinkedIn.`,
          },
        ].map((section, index) => (
          <div key={index} className="space-y-3">
            <h2 className="text-lg font-semibold text-[#b99400] dark:text-[#facc15] tracking-wide">
              {section.title}
            </h2>
            <p className="text-gray-700 dark:text-gray-300 whitespace-pre-line">{section.body}</p>
            {index !== 7 && <Separator className="my-4 dark:bg-zinc-600" />}
          </div>
        ))}
      </Card>

      {/* Footer Note */}
      <p className="text-center text-xs text-gray-500 dark:text-gray-400 mt-8">
        Last updated: July 14, 2025
      </p>
    </main>
  );
};

export default TermsAndConditions;
